
name: Deploy Lambda
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Zip Lambda function
        run: |
          zip -r lambda_monthly_report.zip lambda

      - name: Upload to S3 or trigger deployment (optional)
        run: |
          echo "You can customize this step to deploy to AWS"
